github.com:
    users:
        jodaaisupport-commits:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: jodaaisupport-commits
